version: "3.7"
services:
  postgresql:
    image: postgres:14
    volumes:
      - ./database/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: eva
      POSTGRES_USER: eva
      POSTGRES_PASSWORD: eva
    ports:
      - "5431:5432"
